### ISSUE TITLE
windows builds can't handle '<' in file names

### ISSUE THREAD

**Issue by sezero** [psi29a/unsf#12]
With ftp://ftp.personalcopy.net/pub/PCLite.sfArk.exe  :

....>unsf PCLite.sf2
Reading PCLite.sf2
Writing out to: ./
Opened ./PCLite.cfg for writing.

Could not open patch file ./PCLite-B0/<amac-OvdG.pat

Could not open patch file ./PCLite-B0/<amac-DistG.pat
Finished!

**Comment by psi29a** [comment]
weird, but ntfs and fat have support > , i think, so i'm not sure what is causing this. :/

**Comment by psi29a** [comment]
Was this on linux?

**Comment by sezero** [comment]
Windows builds have the failure on windows...

**Comment by psi29a** [comment]
next thing i'll work on... but don't have a windows machine handy. time to wire up appveyor.

**Comment by psi29a** [comment]
https://answers.microsoft.com/en-us/windows/forum/windows_vista-files/the-source-file-names-are-larger-than-is-supported/438a20a7-a964-4325-b755-8b5d75ddd15b?auth=1

```
Use any character in the current code page for a name, including Unicode characters and characters in the extended character set (128–255), except for the following:
The following reserved characters:
<` (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```

**Comment by psi29a** [comment]
https://support.microsoft.com/en-us/kb/177506

```
When you attempt to create, save, or rename a file, folder, or shortcut, you may receive one of the following error messages:
A filename cannot contain any of the following characters:
\ / : * ? " < > |
```

Not sure this is our problem, but that of the soundfont creators.

**Comment by psi29a** [comment]
This means, for windows builds... we'll have to blacklist these.

**Comment by sezero** [comment]
> This means, for windows builds... we'll have to blacklist these.

Or you can replace them with something sensible (don't know what that would be.)

**Comment by psi29a** [comment]
My vote is for _ or .

**Comment by sezero** [comment]
> My vote is for _ or .

Underscore is usually good. (Unless hopefully it doesn't create
duplicate names.)

**Comment by psi29a** [comment]
We can use a set of 9 alternate symbols.

**Comment by sezero** [comment]
> We can use a set of 9 alternate symbols.

The chances of name collision should be pretty low.
