### ISSUE TITLE
using absolute paths with -O is broken

### ISSUE THREAD

**Issue by sezero** [psi29a/unsf#13]
./unsf -v -O /home/me/10/
creates home/me/10/xxxx under the current directory and
further creation of pat files naturally fail.

the reason is strtok() eats the leading '/' character.
- will cook something to eliminate strtok() usage
- will also cook something to eliminate unsf_concat()
  in order to eliminate repeated malloc() and free and
  use [1024] sized stack buffers.

Also broken (or bad) is that -O expects a tailing '/'
character, which is not user friendly. Will also cook
something for it hopefully.

**Comment by sezero** [comment]
See https://github.com/psi29a/unsf/pull/11/commits/67be0016c5a2338c1ea0ce5e351bedf7262fb3ff fixing the main bug.

See https://github.com/psi29a/unsf/pull/11/commits/8260bb7ba7a241e028c2c3c57eb028d73c82b677 eliminating unsf_concat()

**Comment by psi29a** [comment]
Yeah, I didn't expect anyone to be helping me otherwise I would have left better notes of what works and what doesn't. ;)

**Comment by psi29a** [comment]
I have something for this now. :)
