### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by tntboom5656** [psi29a/unsf#31]
Could you make this available on Windows 10? Or is it just going to be for Linux?

**Comment by psi29a** [comment]
It works on literally any platform...  that can compile C. So yes, It works on windows. :)
vcjob files are provided.

**Comment by tntboom5656** [comment]
Umm, I can't get it to run under windows or linux.

**Comment by psi29a** [comment]
What are you trying to do? Can you give any more details? What doesn't run? Are there any error messages?

**Comment by tntboom5656** [comment]
nvm, I got it to run under Ubuntu 20.04.

**Comment by psi29a** [comment]
So...  can we close this?
